server:
  port: 8086
girl:
  cupSize: A
  age: 18
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://192.168.120.209/sell?characterEncoding=utf-8&useSSL=false
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
    redis:
      host: 192.168.0.105
      port: 6379


